import { SiteLayout } from './components/SiteLayout.jsx';
import siirLogo from '../assets/siir.svg';
import AppScreenshot from './components/AppScreenshot.jsx';


export default function SiirPage() {
  return (
    <SiteLayout site="siir">
<main id="main"><section className="hero app-hero"><div><img className="app-name mark" src={siirLogo} alt="sIIr" width="180" height="118" /><p className="eyebrow">A music observatory for Android</p><h1>A closer look<br />at what you hear.</h1><p className="intro">Explore sound, watch it flow, and grow music from simple rules. For the curious, with the mathematics always close at hand.</p><div className="actions"><a className="button primary" href="https://github.com/siirsuite/siir/releases/latest">Download Android APK</a><a className="button" href="#explore">Look inside</a></div><p className="small">Android 7.0+ · Open source · On-device analysis</p></div><div className="phone-pair"><AppScreenshot className="phone" name="spectrogram" alt="Siir analyzer displaying a spectrogram of an audio recording" width="1080" height="2400" /><AppScreenshot className="phone" name="beat-tracking" alt="Siir beat tracker showing rhythmic pulses in an audio recording" width="1080" height="2400" /></div></section>
<div id="explore"><section className="feature"><div className="feature-copy"><p className="eyebrow">01 / Analyze</p><h2>Listen with your eyes.</h2><p>Bring a recording or use your microphone. Move from the waveform to the frequencies, rhythms, and patterns hidden inside it.</p><ul><li>Spectrograms and pitch-class analysis</li><li>Beat tracking and audio descriptors</li><li>Correlation, self-similarity, and structure</li><li>Zoom into plots and mark moments</li></ul></div><div className="feature-images"><AppScreenshot className="phone" loading="lazy" name="pitch-classes" alt="CQT pitch classes showing the notes present in an audio recording" width="1080" height="2400" /><AppScreenshot className="phone" loading="lazy" name="self-similarity" alt="Self-similarity matrix revealing repeating sections of audio" width="1080" height="2400" /></div></section>
<section className="feature reverse"><div className="feature-copy"><p className="eyebrow">02 / Generate</p><h2>Simple rules.<br />Unexpected melodies.</h2><p>Grow music from cellular automata. Change the seed, choose a rule, and hear a pattern turn into a composition.</p><ul><li>Edit seeds, rules, scales, and tempo</li><li>Play and loop your composition</li><li>Export the result as a WAV file</li></ul></div><div className="feature-images"><AppScreenshot className="phone" loading="lazy" name="cellular-music" alt="Cellular music generator showing a Rule 30 pattern and musical controls" width="1080" height="2400" /></div></section>
<section className="feature"><div className="feature-copy"><p className="eyebrow">03 / Visualize</p><h2>Let sound flow.</h2><p>Watch music move through colorful ink. Touch to stir it, adjust its sensitivity and persistence, or take it fullscreen.</p><p className="small">An experiment in fluid motion, still being refined.</p></div><div className="feature-images"><AppScreenshot className="phone" loading="lazy" name="fluid" alt="Colorful flowing ink responding to music in the fluid visualizer" width="1080" height="2400" /></div></section>
<section className="feature reverse"><div className="feature-copy"><p className="eyebrow">04 / Understand</p><h2>The maths is<br />part of the experience.</h2><p>Open Maths inside the app for the intuition and equations behind the tools. Follow an idea from what you hear to how it works.</p><p>From frequency analysis to beat tracking, Siir leaves room for both curiosity and a closer look.</p></div><div className="feature-images"><AppScreenshot className="phone" loading="lazy" name="spectrogram-maths" alt="In-app explanation of the spectrogram, including equations and attribution" width="1080" height="2400" /></div></section></div>
<section className="download" id="download"><p className="eyebrow">Made to be explored</p><h2>Your next listening session,<br />with a little more curiosity.</h2><p>Download Siir from GitHub and install the APK on your Android device.</p><div className="actions"><a className="button primary" href="https://github.com/siirsuite/siir/releases/latest">Download Android APK</a><a className="button" href="https://github.com/siirsuite/siir">Source code</a></div><p className="small">Requires Android 7.0 or later.</p></section>
<section className="faq" aria-labelledby="questions"><h2 id="questions">A few practical notes</h2><details><summary>How do I install Siir?</summary><p>Open the latest GitHub release and download <code>sIIr-android.apk</code>. Open the file on your Android device. Android may ask you to allow installation from your browser or file manager before you can install it.</p></details><details><summary>Does my audio leave my device?</summary><p>Audio and analysis stay on your device. The microphone is used when you choose live input; you can also explore audio files instead.</p></details><details><summary>What should I know about updates?</summary><p>APKs currently use development signing. Switching between local and GitHub builds may require uninstalling the previous version. Export any work you want to keep before uninstalling.</p></details><details><summary>Can I explore or contribute to the code?</summary><p>Yes. Siir is built with Flutter and is open source. Visit the <a href="https://github.com/siirsuite/siir">GitHub repository</a> for the source, development instructions, and issue tracker.</p></details></section>
</main>
    </SiteLayout>
  );
}
